export interface BenchmarkModelScore {
  name: string;
  score: number; // percentage e.g. 79.3
  highlight?: boolean;
  type: 'titan-ultra' | 'titan-pro' | 'competitor';
  brand: 'titan' | 'openai' | 'anthropic' | 'google' | 'sarvam' | 'deepseek';
}

export interface BenchmarkItem {
  id: string;
  title: string;
  category: 'Agentic' | 'Coding' | 'Reasoning' | 'Tools & MCP' | 'Multimodal';
  domain: string;
  metric: string;
  summary: string;
  description: string;
  evaluationSetup: string;
  titanUltraScore: number;
  titanProScore: number;
  scores: BenchmarkModelScore[];
}

export const BENCHMARKS: BenchmarkItem[] = [
  {
    id: 'terminal-bench',
    title: 'Terminal-Bench 2.1',
    category: 'Agentic',
    domain: 'Agentic Terminal Coding & System Execution',
    metric: 'Task Success Rate (%)',
    summary: 'Multi-turn interactive CLI command execution, shell automation, package debugging, and environment configuration.',
    description: 'Evaluates autonomous agents on complex terminal commands, system administration, automated debugging loops, and bash environment management.',
    evaluationSetup: 'Standard 400 multi-turn CLI tasks in isolated sandboxes, pass@1.',
    titanUltraScore: 61.4,
    titanProScore: 49.8,
    scores: [
      { name: 'Titan Ultra Thinking', score: 61.4, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'GPT-5.6 Sol', score: 73.0, type: 'competitor', brand: 'openai' },
      { name: 'Claude Sonnet 5', score: 68.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.6 Flash', score: 60.0, type: 'competitor', brand: 'google' },
      { name: 'Titan Pro', score: 49.8, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'Ornith-1.0-9B', score: 43.1, type: 'competitor', brand: 'sarvam' },
      { name: 'Llama 4 Scout', score: 35.0, type: 'competitor', brand: 'sarvam' },
      { name: 'Qwen 3.5 9B', score: 21.3, type: 'competitor', brand: 'deepseek' },
      { name: 'Gemma 2 9B IT', score: 18.0, type: 'competitor', brand: 'google' },
    ],
  },
  {
    id: 'swe-bench-pro',
    title: 'SWE-bench Pro',
    category: 'Agentic',
    domain: 'Real-World Multi-File SWE Tasks',
    metric: 'Resolved (%)',
    summary: 'Autonomous end-to-end repository modification, test validation, and multi-file refactoring across large codebases.',
    description: 'Gold-standard benchmark assessing the ability to resolve real GitHub issues spanning multiple source files, complex dependencies, and git worktrees.',
    evaluationSetup: 'Real GitHub repositories, test suite execution in Docker containers.',
    titanUltraScore: 55.8,
    titanProScore: 46.3,
    scores: [
      { name: 'Titan Ultra Thinking', score: 55.8, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro', score: 46.3, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Sol', score: 51.4, type: 'competitor', brand: 'openai' },
      { name: 'Claude Sonnet 5', score: 50.2, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.6 Flash', score: 43.8, type: 'competitor', brand: 'google' },
      { name: 'Ornith-1.0-9B', score: 42.9, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'swe-bench-verified',
    title: 'SWE-bench Verified',
    category: 'Agentic',
    domain: 'Human-Verified Bug Resolutions',
    metric: 'Resolved (%)',
    summary: '500 human-validated real GitHub software engineering issues with clean unit test verification.',
    description: 'A curated subset of SWE-bench rigorously validated by human software engineers for unambiguous problem statements and clean unit test verification.',
    evaluationSetup: 'Pass@1 on 500 validated issues with zero test leakage.',
    titanUltraScore: 87.0,
    titanProScore: 73.1,
    scores: [
      { name: 'Gemini 3.6 Flash', score: 88.0, type: 'competitor', brand: 'google' },
      { name: 'GPT-5.6 Sol', score: 87.0, type: 'competitor', brand: 'openai' },
      { name: 'Claude Sonnet 5', score: 85.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro', score: 73.1, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'Ornith-1.0-9B', score: 69.4, type: 'competitor', brand: 'sarvam' },
      { name: 'Llama 4 Scout', score: 58.0, type: 'competitor', brand: 'sarvam' },
      { name: 'Qwen 3.5 9B', score: 53.2, type: 'competitor', brand: 'deepseek' },
      { name: 'Gemma 2 9B IT', score: 34.0, type: 'competitor', brand: 'google' },
    ],
  },
  {
    id: 'swe-bench-multilingual',
    title: 'SWE-bench Multilingual',
    category: 'Agentic',
    domain: 'Cross-Language Agentic SWE',
    metric: 'Resolved (%)',
    summary: 'Repository engineering across Python, TypeScript, Rust, Go, Java, and C++ ecosystems.',
    description: 'Measures agentic issue resolution across polyglot enterprise codebases with native build systems (Cargo, Gradle, Go Build, Vite, CMake).',
    evaluationSetup: '350 real multilingual repositories with end-to-end continuous integration runs.',
    titanUltraScore: 73.2,
    titanProScore: 64.1,
    scores: [
      { name: 'Titan Ultra Thinking', score: 73.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 64.1, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 69.8, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 68.6, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 61.4, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 49.2, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'qwen-data-bench',
    title: 'QwenDataBench',
    category: 'Agentic',
    domain: 'Data Science & Analytical Agent',
    metric: 'Task Execution Accuracy (%)',
    summary: 'End-to-end dataset modeling, statistical discovery, and automated visualization pipelines in Jupyter environments.',
    description: 'Assesses exploratory data analysis, statistical model fitting, clean Pandas/Polars transformation, and publication-ready charting synthesis.',
    evaluationSetup: 'Automated execution of 300 data-science workflows against ground truth analytics.',
    titanUltraScore: 78.2,
    titanProScore: 68.7,
    scores: [
      { name: 'Titan Ultra Thinking', score: 78.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 68.7, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'Claude 4.6 Sonnet', score: 72.8, type: 'competitor', brand: 'anthropic' },
      { name: 'GPT-5.6 Luna', score: 71.9, type: 'competitor', brand: 'openai' },
      { name: 'Gemini 3.5 Flash', score: 65.4, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 54.6, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'web-arena',
    title: 'WebArena / WebBench',
    category: 'Agentic',
    domain: 'Interactive Web Agent Navigation',
    metric: 'Task Success Rate (%)',
    summary: 'Multi-step web interaction, e-commerce checkout, CRM updates, dynamic DOM actions, and multi-tab state tracking.',
    description: 'Realistic web navigation benchmark testing autonomous agents on live dynamic websites with complex DOM structures, popups, and stateful carts.',
    evaluationSetup: 'End-to-end web browser automation in headless Chromium sandboxes.',
    titanUltraScore: 63.3,
    titanProScore: 53.9,
    scores: [
      { name: 'Titan Ultra Thinking', score: 63.3, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 53.9, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 59.2, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 58.1, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 51.6, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 42.4, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'livecodebench',
    title: 'LiveCodeBench v6',
    category: 'Coding',
    domain: 'Uncontaminated Algorithmic Code',
    metric: 'Pass@1 (%)',
    summary: 'Recent competitive programming problems from LeetCode, Codeforces, and AtCoder with zero dataset contamination.',
    description: 'Continuously updated coding evaluation ensuring zero contamination, evaluating advanced algorithms, data structures, and edge-case resilience.',
    evaluationSetup: 'Pass@1 on all algorithmic problem suites published post-2025.',
    titanUltraScore: 86.2,
    titanProScore: 72.9,
    scores: [
      { name: 'Titan Ultra Thinking', score: 86.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 72.9, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 81.2, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 80.5, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 74.2, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek-R1', score: 72.8, type: 'competitor', brand: 'deepseek' },
      { name: 'Sarvam 105B', score: 62.4, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'mcp-mark',
    title: 'MCPMark / ToolBench 2.0',
    category: 'Tools & MCP',
    domain: 'Universal MCP & Tool Orchestration',
    metric: 'Schema & Tool Accuracy (%)',
    summary: 'Model Context Protocol (MCP) server integration, JSON schema compliance, parameter resolution, and multi-tool chaining.',
    description: 'Evaluates dynamic tool selection, parameter formatting, nested MCP resource queries, and error recovery across multi-tool sequences.',
    evaluationSetup: '1,200 complex multi-step tool calling scenarios across 40+ MCP servers.',
    titanUltraScore: 89.2,
    titanProScore: 81.0,
    scores: [
      { name: 'Titan Ultra Thinking', score: 89.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 81.0, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 84.2, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 83.5, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 77.8, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 66.2, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'gpqa-diamond',
    title: 'GPQA Diamond',
    category: 'Reasoning',
    domain: 'Graduate-Level Scientific Reasoning',
    metric: 'Accuracy (%)',
    summary: 'PhD-level physics, chemistry, biology, and theoretical reasoning questions crafted with Google-proof criteria.',
    description: 'Written and validated by PhD domain experts with strict Google-proof criteria, evaluating deep multi-hop reasoning without simple search retrieval.',
    evaluationSetup: 'Diamond subset (198 questions), 0-shot CoT evaluation with strict answer extraction.',
    titanUltraScore: 83.8,
    titanProScore: 73.9,
    scores: [
      { name: 'Titan Ultra Thinking', score: 83.8, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 73.9, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'Claude 4.6 Sonnet', score: 85.8, type: 'competitor', brand: 'anthropic' },
      { name: 'GPT-5.6 Luna', score: 80.2, type: 'competitor', brand: 'openai' },
      { name: 'Sarvam 105B', score: 78.7, type: 'competitor', brand: 'sarvam' },
      { name: 'Gemini 3.5 Flash', score: 76.4, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek-R1', score: 72.3, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'aime-2026',
    title: 'AIME 2026 / MATH500',
    category: 'Reasoning',
    domain: 'High-Tier Mathematical Reasoning',
    metric: 'Pass@1 (%)',
    summary: 'American Invitational Mathematics Examination & Olympiad competition problems demanding internal step verification.',
    description: 'Complex combinatorial, algebraic, number theory, and geometric mathematical problems demanding internal step-by-step verification.',
    evaluationSetup: 'Standard AIME + MATH500 benchmarks, pass@1 exact string numerical matching.',
    titanUltraScore: 93.2,
    titanProScore: 83.8,
    scores: [
      { name: 'Titan Ultra Thinking', score: 93.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Sarvam 105B', score: 88.3, type: 'competitor', brand: 'sarvam' },
      { name: 'GPT-5.6 Luna', score: 89.0, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 87.4, type: 'competitor', brand: 'anthropic' },
      { name: 'DeepSeek-R1', score: 87.2, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking', score: 83.8, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'Gemini 3.5 Flash', score: 80.5, type: 'competitor', brand: 'google' },
    ],
  },
  {
    id: 'mmmu',
    title: 'MMMU (Multimodal)',
    category: 'Multimodal',
    domain: 'Multidisciplinary College Reasoning',
    metric: 'Accuracy (%)',
    summary: 'Visual reasoning across 30 college subjects (Engineering, Medicine, Physics, Economics) requiring schematic parsing.',
    description: 'Complex multimodal questions requiring diagram parsing, structural schematic interpretation, mathematical charts, and spatial understanding.',
    evaluationSetup: 'Validation subset, standard zero-shot multimodal inference.',
    titanUltraScore: 78.4,
    titanProScore: 69.8,
    scores: [
      { name: 'Titan Ultra Thinking', score: 78.4, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 69.8, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 74.8, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 73.6, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 72.1, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 58.4, type: 'competitor', brand: 'sarvam' },
    ],
  },
  {
    id: 'real-world-qa',
    title: 'RealWorldQA / Vision-Bench',
    category: 'Multimodal',
    domain: 'Physical & Spatial Scene Reasoning',
    metric: 'Accuracy (%)',
    summary: 'Spatial orientation, real-world physical comprehension, and video/camera feed understanding from wearable devices.',
    description: 'Tests visual spatial comprehension on unedited real-world captured images and wearable device camera feeds.',
    evaluationSetup: '700 diverse real-world photographic scenes with ground truth physical verification.',
    titanUltraScore: 86.9,
    titanProScore: 78.7,
    scores: [
      { name: 'Titan Ultra Thinking', score: 86.9, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Titan Pro Thinking', score: 78.7, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5.6 Luna', score: 82.4, type: 'competitor', brand: 'openai' },
      { name: 'Claude 4.6 Sonnet', score: 81.2, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.5 Flash', score: 78.5, type: 'competitor', brand: 'google' },
      { name: 'Sarvam 105B', score: 64.8, type: 'competitor', brand: 'sarvam' },
    ],
  },
];
