export interface BenchmarkModelScore {
  name: string;
  score: number; // percentage e.g. 79.3
  highlight?: boolean;
  type: 'titan-ultra' | 'titan-pro' | 'competitor';
  brand: 'titan' | 'openai' | 'anthropic' | 'google' | 'sarvam' | 'deepseek';
}

export interface BenchmarkItem {
  id: string;
  title: string;
  category: 'Agentic' | 'Coding' | 'Reasoning' | 'Tools & MCP' | 'Multimodal';
  domain: string;
  metric: string;
  summary: string;
  description: string;
  evaluationSetup: string;
  titanUltraScore: number;
  titanProScore: number;
  scores: BenchmarkModelScore[];
}

export const BENCHMARKS: BenchmarkItem[] = [
  {
    id: 'terminal-bench',
    title: 'Terminal-Bench 2.0 / 2.1',
    category: 'Agentic',
    domain: 'Agentic Terminal Coding & CLI System Execution',
    metric: 'Task Success Rate (%)',
    summary: 'Multi-turn interactive CLI command execution, shell automation, package debugging, and environment configuration.',
    description: 'Evaluates autonomous agents on complex terminal commands, system administration, automated debugging loops, and bash environment management.',
    evaluationSetup: 'Standard 400 multi-turn CLI tasks in isolated sandboxes, pass@1.',
    titanUltraScore: 61.4,
    titanProScore: 49.8,
    scores: [
      { name: 'GPT-5.5', score: 82.7, type: 'competitor', brand: 'openai' },
      { name: 'Gemini 3.1 Pro', score: 68.5, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek V4-Pro', score: 67.9, type: 'competitor', brand: 'deepseek' },
      { name: 'Claude Opus 4.6', score: 65.4, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Ultra Thinking (27B)', score: 61.4, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Sonnet 4.6', score: 51.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro Thinking (9B)', score: 49.8, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek V3.2', score: 46.4, type: 'competitor', brand: 'deepseek' },
      { name: 'GPT-5', score: 35.2, type: 'competitor', brand: 'openai' },
    ],
  },
  {
    id: 'swe-bench-pro',
    title: 'SWE-bench Pro',
    category: 'Agentic',
    domain: 'Real-World Multi-File SWE Tasks',
    metric: 'Resolved (%)',
    summary: 'Autonomous end-to-end repository modification, test validation, and multi-file refactoring across large codebases.',
    description: 'Gold-standard benchmark assessing the ability to resolve real GitHub issues spanning multiple source files, complex dependencies, and git worktrees.',
    evaluationSetup: 'Real GitHub repositories, test suite execution in Docker containers.',
    titanUltraScore: 55.8,
    titanProScore: 46.3,
    scores: [
      { name: 'GPT-5.5', score: 58.6, type: 'competitor', brand: 'openai' },
      { name: 'Titan Ultra Thinking (27B)', score: 55.8, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Opus 4.6', score: 54.2, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.1 Pro', score: 52.8, type: 'competitor', brand: 'google' },
      { name: 'Claude Sonnet 4.6', score: 49.5, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro Thinking (9B)', score: 46.3, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek V4-Pro', score: 45.1, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'swe-bench-verified',
    title: 'SWE-bench Verified',
    category: 'Agentic',
    domain: 'Human-Verified Bug Resolutions',
    metric: 'Resolved (%)',
    summary: '500 human-validated real GitHub software engineering issues with clean unit test verification.',
    description: 'A curated subset of SWE-bench rigorously validated by human software engineers for unambiguous problem statements and clean unit test verification.',
    evaluationSetup: 'Pass@1 on 500 validated issues with zero test leakage.',
    titanUltraScore: 82.4,
    titanProScore: 73.1,
    scores: [
      { name: 'Claude Opus 4.6', score: 80.84, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.1 Pro', score: 80.6, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek V4-Pro', score: 80.6, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Ultra Thinking (27B)', score: 82.4, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Gemini 3 Flash', score: 78.0, type: 'competitor', brand: 'google' },
      { name: 'Claude Sonnet 4.5', score: 77.2, type: 'competitor', brand: 'anthropic' },
      { name: 'GPT-5', score: 74.9, type: 'competitor', brand: 'openai' },
      { name: 'Claude Sonnet 4.6', score: 74.6, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro Thinking (9B)', score: 73.1, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek V3.2', score: 73.1, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'swe-bench-multilingual',
    title: 'SWE-bench Multilingual',
    category: 'Agentic',
    domain: 'Cross-Language Agentic SWE',
    metric: 'Resolved (%)',
    summary: 'Repository engineering across Python, TypeScript, Rust, Go, Java, and C++ ecosystems.',
    description: 'Measures agentic issue resolution across polyglot enterprise codebases with native build systems (Cargo, Gradle, Go Build, Vite, CMake).',
    evaluationSetup: '350 real multilingual repositories with end-to-end continuous integration runs.',
    titanUltraScore: 78.5,
    titanProScore: 68.2,
    scores: [
      { name: 'Titan Ultra Thinking (27B)', score: 78.5, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Opus 4.6', score: 77.83, type: 'competitor', brand: 'anthropic' },
      { name: 'GPT-5.5', score: 75.4, type: 'competitor', brand: 'openai' },
      { name: 'Gemini 3.1 Pro', score: 74.2, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek V4-Pro', score: 71.9, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking (9B)', score: 68.2, highlight: true, type: 'titan-pro', brand: 'titan' },
    ],
  },
  {
    id: 'livecodebench',
    title: 'LiveCodeBench',
    category: 'Coding',
    domain: 'Uncontaminated Algorithmic Code',
    metric: 'Pass@1 (%)',
    summary: 'Recent competitive programming problems from LeetCode, Codeforces, and AtCoder with zero dataset contamination.',
    description: 'Continuously updated coding evaluation ensuring zero contamination, evaluating advanced algorithms, data structures, and edge-case resilience.',
    evaluationSetup: 'Pass@1 on algorithmic problem suites published 2025–2026.',
    titanUltraScore: 88.6,
    titanProScore: 78.4,
    scores: [
      { name: 'DeepSeek V4-Pro', score: 93.5, type: 'competitor', brand: 'deepseek' },
      { name: 'Claude Opus 4.6', score: 91.2, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.1 Pro', score: 89.4, type: 'competitor', brand: 'google' },
      { name: 'Titan Ultra Thinking (27B)', score: 88.6, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'GPT-5.5', score: 88.7, type: 'competitor', brand: 'openai' },
      { name: 'Claude Sonnet 4.6', score: 86.5, type: 'competitor', brand: 'anthropic' },
      { name: 'DeepSeek V3.2', score: 83.3, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking (9B)', score: 78.4, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek R1', score: 72.8, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'gpqa-diamond',
    title: 'GPQA Diamond',
    category: 'Reasoning',
    domain: 'Graduate-Level Scientific Reasoning',
    metric: 'Accuracy (%)',
    summary: 'PhD-level physics, chemistry, biology, and theoretical reasoning questions crafted with Google-proof criteria.',
    description: 'Written and validated by PhD domain experts with strict Google-proof criteria, evaluating deep multi-hop reasoning without simple search retrieval.',
    evaluationSetup: 'Diamond subset (198 questions), 0-shot CoT evaluation with strict answer extraction.',
    titanUltraScore: 89.6,
    titanProScore: 79.2,
    scores: [
      { name: 'Gemini 3.1 Pro', score: 94.3, type: 'competitor', brand: 'google' },
      { name: 'Claude Opus 4.6', score: 91.3, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3 Flash', score: 90.4, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek V4-Pro', score: 90.1, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Ultra Thinking (27B)', score: 89.6, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'GPT-5', score: 88.4, type: 'competitor', brand: 'openai' },
      { name: 'Claude Opus 4.5', score: 87.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Claude Sonnet 4.5', score: 83.4, type: 'competitor', brand: 'anthropic' },
      { name: 'DeepSeek V3.2', score: 82.4, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking (9B)', score: 79.2, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek R1', score: 71.5, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'aime-2025',
    title: 'AIME 2025 / 2026',
    category: 'Reasoning',
    domain: 'High-Tier Mathematical Reasoning',
    metric: 'Pass@1 (%)',
    summary: 'American Invitational Mathematics Examination & Olympiad competition problems demanding internal step verification.',
    description: 'Complex combinatorial, algebraic, number theory, and geometric mathematical problems demanding internal step-by-step verification.',
    evaluationSetup: 'Standard AIME + MATH500 benchmarks, pass@1 exact string numerical matching.',
    titanUltraScore: 95.8,
    titanProScore: 86.4,
    scores: [
      { name: 'Titan Ultra Thinking (27B)', score: 95.8, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Opus 4.6', score: 95.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.1 Pro', score: 95.0, type: 'competitor', brand: 'google' },
      { name: 'DeepSeek V4-Pro', score: 95.0, type: 'competitor', brand: 'deepseek' },
      { name: 'GPT-5', score: 94.6, type: 'competitor', brand: 'openai' },
      { name: 'DeepSeek V3.2', score: 93.1, type: 'competitor', brand: 'deepseek' },
      { name: 'Claude Sonnet 4.5', score: 87.0, type: 'competitor', brand: 'anthropic' },
      { name: 'DeepSeek R1', score: 86.7, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking (9B)', score: 86.4, highlight: true, type: 'titan-pro', brand: 'titan' },
    ],
  },
  {
    id: 'hle',
    title: "Humanity's Last Exam (HLE)",
    category: 'Reasoning',
    domain: 'Ultra-Hard Multidisciplinary Benchmark',
    metric: 'Accuracy without tools (%)',
    summary: "The most difficult frontier benchmark curated across graduate and research academia worldwide.",
    description: "Evaluates models on hundreds of PhD-level edge questions designed to challenge human and machine intelligence limits.",
    evaluationSetup: "0-shot closed-book evaluation on official HLE test split.",
    titanUltraScore: 41.2,
    titanProScore: 29.8,
    scores: [
      { name: 'Gemini 3.1 Pro', score: 44.4, type: 'competitor', brand: 'google' },
      { name: 'Claude Opus 4.6', score: 40.0, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Ultra Thinking (27B)', score: 41.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'DeepSeek V4-Pro', score: 37.7, type: 'competitor', brand: 'deepseek' },
      { name: 'Gemini 3 Flash', score: 33.7, type: 'competitor', brand: 'google' },
      { name: 'Titan Pro Thinking (9B)', score: 29.8, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5', score: 26.0, type: 'competitor', brand: 'openai' },
      { name: 'DeepSeek V3.2', score: 25.1, type: 'competitor', brand: 'deepseek' },
    ],
  },
  {
    id: 'arc-agi-2',
    title: 'ARC-AGI-2',
    category: 'Reasoning',
    domain: 'Abstract Visual Pattern Induction',
    metric: 'Pass@1 (%)',
    summary: 'François Chollet abstract pattern reasoning test requiring synthesis of novel transformation rules.',
    description: 'Tests genuine generalization capability on novel grid puzzle transformations that cannot be solved via memorization.',
    evaluationSetup: 'Standard ARC-AGI-2 public evaluation set.',
    titanUltraScore: 71.4,
    titanProScore: 56.2,
    scores: [
      { name: 'Gemini 3.1 Pro', score: 77.1, type: 'competitor', brand: 'google' },
      { name: 'Titan Ultra Thinking (27B)', score: 71.4, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Opus 4.6', score: 68.8, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro Thinking (9B)', score: 56.2, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'GPT-5', score: 54.0, type: 'competitor', brand: 'openai' },
      { name: 'Claude Opus 4.5', score: 37.6, type: 'competitor', brand: 'anthropic' },
    ],
  },
  {
    id: 'mmlu-pro',
    title: 'MMLU-Pro',
    category: 'Reasoning',
    domain: 'Professional-Level Knowledge & Reasoning',
    metric: '10-Choice Accuracy (%)',
    summary: 'Rigorous multi-discipline examination featuring 10 choices per question to minimize guessing baseline.',
    description: 'Higher-difficulty benchmark replacing saturated MMLU with expanded reasoning requirements across biology, law, math, and philosophy.',
    evaluationSetup: 'Standard 5-shot evaluation on official MMLU-Pro dataset.',
    titanUltraScore: 86.8,
    titanProScore: 80.4,
    scores: [
      { name: 'Claude Opus 4.6', score: 88.3, type: 'competitor', brand: 'anthropic' },
      { name: 'DeepSeek V4-Pro', score: 87.5, type: 'competitor', brand: 'deepseek' },
      { name: 'Gemini 3.1 Pro', score: 86.8, type: 'competitor', brand: 'google' },
      { name: 'Titan Ultra Thinking (27B)', score: 86.8, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Claude Sonnet 4.6', score: 85.6, type: 'competitor', brand: 'anthropic' },
      { name: 'GPT-5', score: 85.1, type: 'competitor', brand: 'openai' },
      { name: 'DeepSeek V3.2', score: 85.0, type: 'competitor', brand: 'deepseek' },
      { name: 'DeepSeek R1', score: 84.0, type: 'competitor', brand: 'deepseek' },
      { name: 'Titan Pro Thinking (9B)', score: 80.4, highlight: true, type: 'titan-pro', brand: 'titan' },
    ],
  },
  {
    id: 'mmmu',
    title: 'MMMU / MMMU Pro',
    category: 'Multimodal',
    domain: 'Multidisciplinary College Reasoning',
    metric: 'Accuracy (%)',
    summary: 'Visual reasoning across 30 college subjects (Engineering, Medicine, Physics, Economics) requiring schematic parsing.',
    description: 'Complex multimodal questions requiring diagram parsing, structural schematic interpretation, mathematical charts, and spatial understanding.',
    evaluationSetup: 'Validation subset, standard zero-shot multimodal inference.',
    titanUltraScore: 81.6,
    titanProScore: 72.4,
    scores: [
      { name: 'GPT-5', score: 84.2, type: 'competitor', brand: 'openai' },
      { name: 'Titan Ultra Thinking (27B)', score: 81.6, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'Gemini 3 Flash', score: 81.2, type: 'competitor', brand: 'google' },
      { name: 'Claude Sonnet 4.5', score: 77.8, type: 'competitor', brand: 'anthropic' },
      { name: 'Claude Opus 4.6', score: 77.3, type: 'competitor', brand: 'anthropic' },
      { name: 'Titan Pro Thinking (9B)', score: 72.4, highlight: true, type: 'titan-pro', brand: 'titan' },
    ],
  },
  {
    id: 'mcp-mark',
    title: 'MCPMark / ToolBench 2.0',
    category: 'Tools & MCP',
    domain: 'Universal MCP & Tool Orchestration',
    metric: 'Schema & Tool Accuracy (%)',
    summary: 'Model Context Protocol (MCP) server integration, JSON schema compliance, parameter resolution, and multi-tool chaining.',
    description: 'Evaluates dynamic tool selection, parameter formatting, nested MCP resource queries, and error recovery across multi-tool sequences.',
    evaluationSetup: '1,200 complex multi-step tool calling scenarios across 40+ MCP servers.',
    titanUltraScore: 89.2,
    titanProScore: 81.0,
    scores: [
      { name: 'Titan Ultra Thinking (27B)', score: 89.2, highlight: true, type: 'titan-ultra', brand: 'titan' },
      { name: 'GPT-5.5', score: 87.4, type: 'competitor', brand: 'openai' },
      { name: 'Claude Opus 4.6', score: 86.8, type: 'competitor', brand: 'anthropic' },
      { name: 'Gemini 3.1 Pro', score: 85.2, type: 'competitor', brand: 'google' },
      { name: 'Titan Pro Thinking (9B)', score: 81.0, highlight: true, type: 'titan-pro', brand: 'titan' },
      { name: 'DeepSeek V4-Pro', score: 80.5, type: 'competitor', brand: 'deepseek' },
    ],
  },
];
