'use client';

import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, Code, FileCode, Search, X, Sparkles, ExternalLink } from 'lucide-react';
import { Artifact, ChatSession } from '@/types';

interface FilesModalProps {
  isOpen: boolean;
  onClose: () => void;
  sessions: ChatSession[];
  onOpenArtifact?: (artifact: Artifact) => void;
}

export function FilesModal({
  isOpen,
  onClose,
  sessions,
  onOpenArtifact,
}: FilesModalProps) {
  const [filterType, setFilterType] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Collect all artifacts stored across local chat sessions
  const allArtifacts = useMemo(() => {
    if (typeof window === 'undefined') return [];
    const artifactsList: { artifact: Artifact; sessionTitle: string; timestamp: number }[] = [];

    for (const session of sessions) {
      try {
        const stored = localStorage.getItem(`zero_session_${session.id}`);
        if (stored) {
          const messages = JSON.parse(stored);
          if (Array.isArray(messages)) {
            for (const msg of messages) {
              if (msg.artifacts && Array.isArray(msg.artifacts)) {
                for (const art of msg.artifacts) {
                  artifactsList.push({
                    artifact: art,
                    sessionTitle: session.title,
                    timestamp: msg.timestamp || new Date(session.updated_at).getTime(),
                  });
                }
              }
            }
          }
        }
      } catch {}
    }

    return artifactsList;
  }, [sessions, isOpen]);

  const filteredArtifacts = useMemo(() => {
    return allArtifacts.filter(({ artifact, sessionTitle }) => {
      const matchesSearch =
        artifact.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
        sessionTitle.toLowerCase().includes(searchQuery.toLowerCase());

      if (!matchesSearch) return false;
      if (filterType === 'all') return true;
      if (filterType === 'code') return artifact.type === 'code';
      if (filterType === 'documents') return ['markdown', 'md', 'pdf', 'docx'].includes(artifact.type);
      if (filterType === 'data') return ['csv', 'xlsx', 'json'].includes(artifact.type);
      return true;
    });
  }, [allArtifacts, searchQuery, filterType]);

  const handleDownload = (artifact: Artifact, e: React.MouseEvent) => {
    e.stopPropagation();
    const element = document.createElement('a');
    const file = new Blob([artifact.content], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `${artifact.title || 'zero-file'}.${artifact.type === 'code' ? artifact.language || 'txt' : artifact.type}`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  if (!isOpen) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[250] flex items-center justify-center p-4 sm:p-6 font-sans">
        {/* Backdrop */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.15 }}
          className="fixed inset-0 bg-black/50 backdrop-blur-sm"
          onClick={onClose}
        />

        {/* Modal Window */}
        <motion.div
          initial={{ opacity: 0, scale: 0.96, y: 8 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.96, y: 8 }}
          transition={{ type: 'spring', stiffness: 400, damping: 30 }}
          className="relative w-full max-w-3xl h-[560px] max-h-[90vh] bg-white rounded-2xl shadow-2xl border border-[#E5E4DF] overflow-hidden z-10 flex flex-col"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-[#E5E4DF]">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-xl bg-[#00C8FF]/10 text-[#00C8FF] flex items-center justify-center">
                <FileText className="w-4.5 h-4.5" />
              </div>
              <div>
                <h2 className="text-sm font-bold text-[#111]">Files & Artifacts Vault</h2>
                <p className="text-[11.5px] text-[#111]/50">
                  Inspect and download code files, research documents, and data generated by Zero
                </p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-[#111]/40 hover:text-[#111] hover:bg-[#F0F0F0]"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {/* Filter Bar */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-3 px-6 py-3 bg-[#F9F8F5] border-b border-[#E5E4DF]">
            <div className="flex items-center gap-1.5 w-full sm:w-auto overflow-x-auto pb-1 sm:pb-0">
              {['all', 'code', 'documents', 'data'].map((tab) => (
                <button
                  key={tab}
                  type="button"
                  onClick={() => setFilterType(tab)}
                  className={`px-3 py-1 rounded-lg text-xs font-semibold capitalize transition-all ${
                    filterType === tab
                      ? 'bg-white text-[#111] shadow-xs border border-[#E5E4DF]'
                      : 'text-[#111]/60 hover:text-[#111]'
                  }`}
                >
                  {tab}
                </button>
              ))}
            </div>

            <div className="relative w-full sm:w-64">
              <Search className="w-3.5 h-3.5 text-[#111]/40 absolute left-3 top-2.5" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Filter files..."
                className="w-full pl-8 pr-3 py-1.5 bg-white border border-[#E5E4DF] rounded-xl text-xs text-[#111] outline-none focus:border-[#00C8FF]"
              />
            </div>
          </div>

          {/* Files List */}
          <div className="flex-1 overflow-y-auto p-6">
            {filteredArtifacts.length === 0 ? (
              <div className="py-16 text-center">
                <FileCode className="w-10 h-10 text-[#111]/25 mx-auto mb-2" />
                <p className="text-xs font-semibold text-[#111]/60">No files found</p>
                <p className="text-[11.5px] text-[#111]/40 mt-1 max-w-sm mx-auto">
                  When Zero generates code blocks, documents, or data sheets, they automatically get indexed here.
                </p>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {filteredArtifacts.map(({ artifact, sessionTitle }, idx) => (
                  <div
                    key={`${artifact.id}-${idx}`}
                    onClick={() => {
                      if (onOpenArtifact) {
                        onOpenArtifact(artifact);
                        onClose();
                      }
                    }}
                    className="flex flex-col justify-between p-3.5 rounded-xl border border-[#E5E4DF] hover:border-[#00C8FF]/40 hover:shadow-sm bg-[#FDFDFB] transition-all cursor-pointer group"
                  >
                    <div className="flex items-start gap-3">
                      <div className="w-8 h-8 rounded-lg bg-[#00C8FF]/10 text-[#00C8FF] flex items-center justify-center shrink-0">
                        {artifact.type === 'code' ? (
                          <Code className="w-4 h-4" />
                        ) : (
                          <FileText className="w-4 h-4" />
                        )}
                      </div>
                      <div className="min-w-0 flex-1">
                        <div className="text-xs font-bold text-[#111] truncate group-hover:text-[#00C8FF] transition-colors">
                          {artifact.title || 'Untitled Document'}
                        </div>
                        <div className="text-[10.5px] text-[#111]/45 truncate mt-0.5">
                          In: {sessionTitle}
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center justify-between pt-3 mt-2 border-t border-[#E5E4DF]/60 text-[10.5px]">
                      <span className="font-semibold uppercase tracking-wider text-[#111]/40">
                        {artifact.language || artifact.type}
                      </span>
                      <button
                        type="button"
                        onClick={(e) => handleDownload(artifact, e)}
                        className="flex items-center gap-1 text-[#00C8FF] hover:underline font-semibold"
                        title="Download file"
                      >
                        <Download className="w-3 h-3" /> Download
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
